# Import the relevant libraries

In [1]:
import numpy as np

## Transposing matrices

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [5]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [6]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [7]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

## Transposing scalars

In [8]:
s = np.array([5])

In [9]:
s.T

array([5])

## Transposing vectors

In [10]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [11]:
x.T

array([1, 2, 3])

In [12]:
x.shape

(3,)

In [13]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [14]:
x_reshaped.T

array([[1],
       [2],
       [3]])